
CREATE TABLE BIDDING_REQUEST_LIST
(
	BIDDING_REQUEST_NO   NUMBER(10) NOT NULL ,
	GOVERNMENT_BUSINESS_BOARD_NO NUMBER(10) NULL ,
	BUSINESS_PLAN        VARCHAR2(100) NULL ,
	BIDDING_REQUEST_DATE DATE NULL ,
	BIDDING_STATUS       VARCHAR2(6) NULL ,
	BIDDING_DATE         DATE NULL ,
	LANDSCAPING_FIELD_BUSINESS_NO NUMBER(10) NULL 
);



CREATE UNIQUE INDEX XPK입찰신청리스트 ON BIDDING_REQUEST_LIST
(BIDDING_REQUEST_NO   ASC);



ALTER TABLE BIDDING_REQUEST_LIST
	ADD CONSTRAINT  XPK입찰신청리스트 PRIMARY KEY (BIDDING_REQUEST_NO);



CREATE TABLE BUSINESS_PROGRESS
(
	BUSINESS_PROGRESS_NO NUMBER(10) NOT NULL ,
	GROUP_NO             NUMBER(10) NULL ,
	ORDER_NUMBER         NUMBER(10) NULL ,
	PROGRESS_REGISTRATION_DATE DATE NULL ,
	PROGRESS_TITLE       VARCHAR2(300) NULL ,
	PROGRESS_DETAILED    VARCHAR2(1024) NULL ,
	LANDSCAPING_ENTERPRISE_NO NUMBER(10) NULL ,
	PUBLIC_OFFICIAL_NO   NUMBER(10) NULL 
);



CREATE UNIQUE INDEX XPK사업진행현황 ON BUSINESS_PROGRESS
(BUSINESS_PROGRESS_NO   ASC);



ALTER TABLE BUSINESS_PROGRESS
	ADD CONSTRAINT  XPK사업진행현황 PRIMARY KEY (BUSINESS_PROGRESS_NO);



CREATE TABLE CITIES
(
	CITIES_NO            NUMBER(10) NOT NULL ,
	CITIES_NAME          VARCHAR2(50) NULL ,
	METROPOLITAN_CITY_NO NUMBER(10) NULL 
);



CREATE UNIQUE INDEX XPK시군구 ON CITIES
(CITIES_NO   ASC);



ALTER TABLE CITIES
	ADD CONSTRAINT  XPK시군구 PRIMARY KEY (CITIES_NO);



CREATE TABLE FIELD_OF_BUSINESS
(
	FIELD_OF_BUSINESS_NO NUMBER(10) NOT NULL ,
	FIELD_OF_BUSINESS_NAME VARCHAR2(60) NULL 
);



CREATE UNIQUE INDEX XPK사업분야 ON FIELD_OF_BUSINESS
(FIELD_OF_BUSINESS_NO   ASC);



ALTER TABLE FIELD_OF_BUSINESS
	ADD CONSTRAINT  XPK사업분야 PRIMARY KEY (FIELD_OF_BUSINESS_NO);



CREATE TABLE GOVERNMENT_BUSINESS_BOARD
(
	GOVERNMENT_BUSINESS_BOARD_NO NUMBER(10) NOT NULL ,
	BUSINESS_TITLE       VARCHAR2(100) NULL ,
	ESTIMATED_AMOUNT_OF_BUSINESS NUMBER(20) NULL ,
	REGISTRATION_DATE    DATE NULL ,
	BUSINESS_DETAILS     VARCHAR2(1024) NULL ,
	PUBLIC_OFFICIAL_NO   NUMBER(10) NULL ,
	GOVERNMENT_PUBLICLY_ANNOUNCED DATE NULL ,
	BUSINESS_START_DATE  DATE NULL ,
	FIELD_OF_BUSINESS_NO NUMBER(10) NULL ,
	BUSINESS_END_DATE    DATE NULL 
);



CREATE UNIQUE INDEX XPK정부사업공고게시판 ON GOVERNMENT_BUSINESS_BOARD
(GOVERNMENT_BUSINESS_BOARD_NO   ASC);



ALTER TABLE GOVERNMENT_BUSINESS_BOARD
	ADD CONSTRAINT  XPK정부사업공고게시판 PRIMARY KEY (GOVERNMENT_BUSINESS_BOARD_NO);



CREATE TABLE LANDSCAPING_ENTERPRISE
(
	LANDSCAPING_ENTERPRISE_NO NUMBER(10) NOT NULL ,
	LANDSCAPING_ENTERPRISE_ID VARCHAR2(60) NULL ,
	LANDSCAPING_ENTERPRISE_PW VARCHAR2(60) NULL ,
	COMPANY_NAME         VARCHAR2(60) NULL ,
	COMPANY_TEL          VARCHAR2(20) NULL ,
	BUSINESS_REGISTARTION_NUMBER VARCHAR2(60) NULL ,
	CITIES_NO            NUMBER(10) NULL ,
	TOTAL_EMPLOYEES_NUMBER NUMBER(10) NULL ,
	AVAILABLE_STAFF      NUMBER(10) NULL ,
	SALES                NUMBER(20) NULL 
);



CREATE UNIQUE INDEX XPK조경_원예기업 ON LANDSCAPING_ENTERPRISE
(LANDSCAPING_ENTERPRISE_NO   ASC);



ALTER TABLE LANDSCAPING_ENTERPRISE
	ADD CONSTRAINT  XPK조경_원예기업 PRIMARY KEY (LANDSCAPING_ENTERPRISE_NO);



CREATE TABLE LANDSCAPING_FIELD_BUSINESS
(
	LANDSCAPING_ENTERPRISE_NO NUMBER(10) NULL ,
	FIELD_OF_BUSINESS_NO NUMBER(10) NULL ,
	LANDSCAPING_FIELD_BUSINESS_NO NUMBER(10) NOT NULL 
);



CREATE UNIQUE INDEX XPK조경기업별사업분야 ON LANDSCAPING_FIELD_BUSINESS
(LANDSCAPING_FIELD_BUSINESS_NO   ASC);



ALTER TABLE LANDSCAPING_FIELD_BUSINESS
	ADD CONSTRAINT  XPK조경기업별사업분야 PRIMARY KEY (LANDSCAPING_FIELD_BUSINESS_NO);



CREATE TABLE METROPOLITAN_CITY
(
	METROPOLITAN_CITY_NO NUMBER(10) NOT NULL ,
	METROPOLITAN_CITY_NAME VARCHAR2(50) NULL 
);



CREATE UNIQUE INDEX XPK광역시도 ON METROPOLITAN_CITY
(METROPOLITAN_CITY_NO   ASC);



ALTER TABLE METROPOLITAN_CITY
	ADD CONSTRAINT  XPK광역시도 PRIMARY KEY (METROPOLITAN_CITY_NO);



CREATE TABLE PHOTO
(
	PHOTO_NO             NUMBER(10) NOT NULL ,
	PHOTO_LINK           VARCHAR2(1024) NULL ,
	PHOTO_NAME           VARCHAR2(60) NULL ,
	PHOTO_SUBCATEGORY_NO NUMBER(10) NULL 
);



CREATE UNIQUE INDEX XPK사진자료 ON PHOTO
(PHOTO_NO   ASC);



ALTER TABLE PHOTO
	ADD CONSTRAINT  XPK사진자료 PRIMARY KEY (PHOTO_NO);



CREATE TABLE PHOTO_MIDDLE_CLASSIFICATION
(
	PHOTO_MIDDLE_CLASSIFICATION_NO NUMBER(10) NOT NULL ,
	PHOTO_MC_NAME        VARCHAR2(60) NULL 
);



CREATE UNIQUE INDEX XPK사진_중분류 ON PHOTO_MIDDLE_CLASSIFICATION
(PHOTO_MIDDLE_CLASSIFICATION_NO   ASC);



ALTER TABLE PHOTO_MIDDLE_CLASSIFICATION
	ADD CONSTRAINT  XPK사진_중분류 PRIMARY KEY (PHOTO_MIDDLE_CLASSIFICATION_NO);



CREATE TABLE PHOTO_SUBCATEGORY
(
	PHOTO_SUBCATEGORY_NO NUMBER(10) NOT NULL ,
	PHOTO_SUBCATEGORY_NAME VARCHAR2(60) NULL ,
	PHOTO_MIDDLE_CLASSIFICATION_NO NUMBER(10) NULL 
);



CREATE UNIQUE INDEX XPK사진_소분류 ON PHOTO_SUBCATEGORY
(PHOTO_SUBCATEGORY_NO   ASC);



ALTER TABLE PHOTO_SUBCATEGORY
	ADD CONSTRAINT  XPK사진_소분류 PRIMARY KEY (PHOTO_SUBCATEGORY_NO);



CREATE TABLE PRI_BIDDING_REQUEST_LIST
(
	PRI_BIDDING_REQUEST_NO NUMBER(10) NOT NULL ,
	PRI_BUSINESS_PLAN    VARCHAR2(100) NULL ,
	PRI_BIDDING_REQUEST_DATE DATE NULL ,
	PRI_BIDDING_STATUS   VARCHAR2(6) NULL ,
	PRI_BIDDING_DATE     DATE NULL ,
	PRI_BUSINESS_BOARD_NO NUMBER(10) NULL ,
	PRI_FIELD_BUSINESS_NO NUMBER(10) NULL 
);



CREATE UNIQUE INDEX XPK민간입찰신청리스트 ON PRI_BIDDING_REQUEST_LIST
(PRI_BIDDING_REQUEST_NO   ASC);



ALTER TABLE PRI_BIDDING_REQUEST_LIST
	ADD CONSTRAINT  XPK민간입찰신청리스트 PRIMARY KEY (PRI_BIDDING_REQUEST_NO);



CREATE TABLE PRI_BUSINESS_BOARD
(
	PRI_BUSINESS_BOARD_NO NUMBER(10) NOT NULL ,
	PRI_BUSINESS_TITLE   VARCHAR2(300) NULL ,
	PRI_EAOF             NUMBER(20) NULL ,
	PRI_REGISTRATION_DATE DATE NULL ,
	PRI_ANNOUNCED        DATE NULL ,
	PRI_BUSINESS_START_DATE DATE NULL ,
	PRI_BUSINESS_DETAILS VARCHAR2(1024) NULL ,
	LANDSCAPING_ENTERPRISE_NO NUMBER(10) NULL ,
	PRI_FIELD_BUSINESS_NO NUMBER(10) NULL ,
	PRI_FIELD_OF_BUSINESS_NO NUMBER(10) NULL 
);



CREATE UNIQUE INDEX XPK민간사업공고게시판 ON PRI_BUSINESS_BOARD
(PRI_BUSINESS_BOARD_NO   ASC);



ALTER TABLE PRI_BUSINESS_BOARD
	ADD CONSTRAINT  XPK민간사업공고게시판 PRIMARY KEY (PRI_BUSINESS_BOARD_NO);



CREATE TABLE PRI_ENTERPRISE
(
	PRI_ENTERPRISE_NO    NUMBER(10) NOT NULL ,
	PRI_ENTERPRISE_NAME  VARCHAR2(60) NULL ,
	PRI_ENTERPRISE_TEL   VARCHAR2(60) NULL ,
	PRI_REGISTRATION_NUMBER VARCHAR2(60) NULL ,
	PRI_ENTERPRISE_ID    VARCHAR2(60) NULL ,
	PRI_ENTERPRISE_PASSWORD VARCHAR2(60) NULL ,
	CITIES_NO            NUMBER(10) NULL 
);



CREATE UNIQUE INDEX XPK민간기업 ON PRI_ENTERPRISE
(PRI_ENTERPRISE_NO   ASC);



ALTER TABLE PRI_ENTERPRISE
	ADD CONSTRAINT  XPK민간기업 PRIMARY KEY (PRI_ENTERPRISE_NO);



CREATE TABLE PRI_FIELD_BUSINESS
(
	PRI_FIELD_BUSINESS_NO NUMBER(10) NOT NULL ,
	PRI_ENTERPRISE_NO    NUMBER(10) NULL ,
	PRI_FIELD_OF_BUSINESS_NO NUMBER(10) NOT NULL 
);



CREATE UNIQUE INDEX XPK민간기업별사업분야 ON PRI_FIELD_BUSINESS
(PRI_FIELD_BUSINESS_NO   ASC);



ALTER TABLE PRI_FIELD_BUSINESS
	ADD CONSTRAINT  XPK민간기업별사업분야 PRIMARY KEY (PRI_FIELD_BUSINESS_NO);



CREATE TABLE PRI_FIELD_OF_BUSINESS
(
	PRI_FIELD_OF_BUSINESS_NO NUMBER(10) NOT NULL ,
	PRI_FIELD_OF_BUSINESS_NAME VARCHAR2(60) NULL 
);



CREATE UNIQUE INDEX XPK사업분야_민간기업 ON PRI_FIELD_OF_BUSINESS
(PRI_FIELD_OF_BUSINESS_NO   ASC);



ALTER TABLE PRI_FIELD_OF_BUSINESS
	ADD CONSTRAINT  XPK사업분야_민간기업 PRIMARY KEY (PRI_FIELD_OF_BUSINESS_NO);



CREATE TABLE PUBLIC_OFFICIAL
(
	PUBLIC_OFFICIAL_NO   NUMBER(10) NOT NULL ,
	PUBLIC_OFFICIAL_ID   VARCHAR2(20) NULL ,
	PASSWORD             VARCHAR2(20) NULL ,
	NAME                 VARCHAR2(20) NULL ,
	AFFILIATED_DEPARTMENT VARCHAR2(20) NULL ,
	CITIES_NO            NUMBER(10) NULL ,
	PUBLIC_OFFICIAL_TEL  VARCHAR2(20) NULL 
);



CREATE UNIQUE INDEX XPK공무원 ON PUBLIC_OFFICIAL
(PUBLIC_OFFICIAL_NO   ASC);



ALTER TABLE PUBLIC_OFFICIAL
	ADD CONSTRAINT  XPK공무원 PRIMARY KEY (PUBLIC_OFFICIAL_NO);



ALTER TABLE BIDDING_REQUEST_LIST
	ADD (CONSTRAINT R_4 FOREIGN KEY (GOVERNMENT_BUSINESS_BOARD_NO) REFERENCES GOVERNMENT_BUSINESS_BOARD (GOVERNMENT_BUSINESS_BOARD_NO) ON DELETE SET NULL);



ALTER TABLE BIDDING_REQUEST_LIST
	ADD (CONSTRAINT R_23 FOREIGN KEY (LANDSCAPING_FIELD_BUSINESS_NO) REFERENCES LANDSCAPING_FIELD_BUSINESS (LANDSCAPING_FIELD_BUSINESS_NO) ON DELETE SET NULL);



ALTER TABLE BUSINESS_PROGRESS
	ADD (CONSTRAINT R_7 FOREIGN KEY (LANDSCAPING_ENTERPRISE_NO) REFERENCES LANDSCAPING_ENTERPRISE (LANDSCAPING_ENTERPRISE_NO) ON DELETE SET NULL);



ALTER TABLE BUSINESS_PROGRESS
	ADD (CONSTRAINT R_8 FOREIGN KEY (PUBLIC_OFFICIAL_NO) REFERENCES PUBLIC_OFFICIAL (PUBLIC_OFFICIAL_NO) ON DELETE SET NULL);



ALTER TABLE CITIES
	ADD (CONSTRAINT R_1 FOREIGN KEY (METROPOLITAN_CITY_NO) REFERENCES METROPOLITAN_CITY (METROPOLITAN_CITY_NO) ON DELETE SET NULL);



ALTER TABLE GOVERNMENT_BUSINESS_BOARD
	ADD (CONSTRAINT R_3 FOREIGN KEY (PUBLIC_OFFICIAL_NO) REFERENCES PUBLIC_OFFICIAL (PUBLIC_OFFICIAL_NO) ON DELETE SET NULL);



ALTER TABLE GOVERNMENT_BUSINESS_BOARD
	ADD (CONSTRAINT R_12 FOREIGN KEY (FIELD_OF_BUSINESS_NO) REFERENCES FIELD_OF_BUSINESS (FIELD_OF_BUSINESS_NO) ON DELETE SET NULL);



ALTER TABLE LANDSCAPING_ENTERPRISE
	ADD (CONSTRAINT R_10 FOREIGN KEY (CITIES_NO) REFERENCES CITIES (CITIES_NO) ON DELETE SET NULL);



ALTER TABLE LANDSCAPING_FIELD_BUSINESS
	ADD (CONSTRAINT R_18 FOREIGN KEY (LANDSCAPING_ENTERPRISE_NO) REFERENCES LANDSCAPING_ENTERPRISE (LANDSCAPING_ENTERPRISE_NO) ON DELETE SET NULL);



ALTER TABLE LANDSCAPING_FIELD_BUSINESS
	ADD (CONSTRAINT R_19 FOREIGN KEY (FIELD_OF_BUSINESS_NO) REFERENCES FIELD_OF_BUSINESS (FIELD_OF_BUSINESS_NO) ON DELETE SET NULL);



ALTER TABLE PHOTO
	ADD (CONSTRAINT R_28 FOREIGN KEY (PHOTO_SUBCATEGORY_NO) REFERENCES PHOTO_SUBCATEGORY (PHOTO_SUBCATEGORY_NO) ON DELETE SET NULL);



ALTER TABLE PHOTO_SUBCATEGORY
	ADD (CONSTRAINT R_27 FOREIGN KEY (PHOTO_MIDDLE_CLASSIFICATION_NO) REFERENCES PHOTO_MIDDLE_CLASSIFICATION (PHOTO_MIDDLE_CLASSIFICATION_NO) ON DELETE SET NULL);



ALTER TABLE PRI_BIDDING_REQUEST_LIST
	ADD (CONSTRAINT R_30 FOREIGN KEY (PRI_BUSINESS_BOARD_NO) REFERENCES PRI_BUSINESS_BOARD (PRI_BUSINESS_BOARD_NO) ON DELETE SET NULL);



ALTER TABLE PRI_BIDDING_REQUEST_LIST
	ADD (CONSTRAINT R_31 FOREIGN KEY (PRI_FIELD_BUSINESS_NO) REFERENCES PRI_FIELD_BUSINESS (PRI_FIELD_BUSINESS_NO) ON DELETE SET NULL);



ALTER TABLE PRI_BUSINESS_BOARD
	ADD (CONSTRAINT R_17 FOREIGN KEY (LANDSCAPING_ENTERPRISE_NO) REFERENCES LANDSCAPING_ENTERPRISE (LANDSCAPING_ENTERPRISE_NO) ON DELETE SET NULL);



ALTER TABLE PRI_BUSINESS_BOARD
	ADD (CONSTRAINT R_22 FOREIGN KEY (PRI_FIELD_BUSINESS_NO) REFERENCES PRI_FIELD_BUSINESS (PRI_FIELD_BUSINESS_NO) ON DELETE SET NULL);



ALTER TABLE PRI_BUSINESS_BOARD
	ADD (CONSTRAINT R_24 FOREIGN KEY (PRI_FIELD_OF_BUSINESS_NO) REFERENCES PRI_FIELD_OF_BUSINESS (PRI_FIELD_OF_BUSINESS_NO) ON DELETE SET NULL);



ALTER TABLE PRI_ENTERPRISE
	ADD (CONSTRAINT R_11 FOREIGN KEY (CITIES_NO) REFERENCES CITIES (CITIES_NO) ON DELETE SET NULL);



ALTER TABLE PRI_FIELD_BUSINESS
	ADD (CONSTRAINT R_20 FOREIGN KEY (PRI_ENTERPRISE_NO) REFERENCES PRI_ENTERPRISE (PRI_ENTERPRISE_NO) ON DELETE SET NULL);



ALTER TABLE PRI_FIELD_BUSINESS
	ADD (CONSTRAINT R_29 FOREIGN KEY (PRI_FIELD_OF_BUSINESS_NO) REFERENCES PRI_FIELD_OF_BUSINESS (PRI_FIELD_OF_BUSINESS_NO));



ALTER TABLE PUBLIC_OFFICIAL
	ADD (CONSTRAINT R_2 FOREIGN KEY (CITIES_NO) REFERENCES CITIES (CITIES_NO) ON DELETE SET NULL);




