build:
	docker build .
run:
	docker run -it --name ubuntu ubuntu7 /bin/bash
exec:
	docker start ubuntu
	docker attach ubuntu
ps:
	docker ps -a
img:
	docker images
rm:
	docker rm ubuntu
rmi:
	docker rmi ubuntu
