#base images
FROM ubuntu:latest

#RUN COMMAND
RUN echo Hello~ Its shell type command.
RUN ["echo", "Hello~ its exec type cmmand."]
RUN ["/bin/bash", "-c", "echo 'Hello~ Its /bin/bash execution in shell type command.'"]
